# Generated by Django 3.1 on 2020-10-22 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeStamp', models.DateTimeField(verbose_name='Data e Hora da Postagem')),
                ('text', models.TextField(verbose_name='Postagem')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeStamp', models.DateTimeField(verbose_name='Data e Hora da Postagem')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='network.post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_reactions', to='account.profile')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where', to='network.reaction')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comment')),
                ('DateTimeStamp', models.DateTimeField(verbose_name='Data e Hora da Postagem')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on', to='network.post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='someone', to='account.profile')),
            ],
        ),
    ]
